### ISSUE TITLE
Python 3.13 is not supported (No module named 'cgi')

### ISSUE THREAD

**Issue by MrMarvel** [JovianML/opendatasets#18]
Python 3.13.0
Windows 10
OpenDatasets 0.1.22
![image](https://github.com/user-attachments/assets/fc5a8ab6-3dc6-451d-8b4b-0ab7ab826a0c)
Also https://docs.python.org/3/whatsnew/3.13.html:
Important removals:
[PEP 594](https://docs.python.org/3/whatsnew/3.13.html#whatsnew313-pep594): The remaining 19 “dead batteries” (legacy stdlib modules) have been removed from the standard library: aifc, audioop,  
**cgi!!**, cgitb, chunk, crypt, imghdr, mailcap, msilib, nis, nntplib, ossaudiodev, pipes, sndhdr, spwd, sunau, telnetlib, uu and xdrlib.

**Comment by MrMarvel** [comment]
As a temporal solution:
for pip
`pip install git+https://github.com/MrMarvel/OpenDatasetsPy313`
for toml UV (package manager) projects example:
```toml
[project]
name = "visualbinarization"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "google-auth~=2.0",
    "matplotlib~=3.0",
    "notebook",
    "opencv-python-headless~=4.0",
    "opendatasets",
]

[tool.uv.sources]
opendatasets = { git = "https://github.com/MrMarvel/OpenDatasetsPy313" }
```
